/// Flutter icons MedicineIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MedicineIcons
///      fonts:
///       - asset: fonts/MedicineIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MedicineIcons {
  MedicineIcons._();

  static const _kFontFam = 'MedicineIcons';

  static const IconData capsule = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData dropper = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData syringe = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData radar = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData syrup = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData tablets = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData antiseptic_cream = const IconData(
      0xe809, fontFamily: _kFontFam);
  static const IconData pill_bottle = const IconData(
      0xe80a, fontFamily: _kFontFam);
}
